### ISSUE TITLE
make 1.5M, 3.0M, and 10M atom systems publicly available

### ISSUE THREAD

**Issue by dotsdl** [ianmkenney/vesicle_library#1]
The largest system in the repository is about 500,000 atoms. Weren't there larger ones as well that were meant to be added?

Asking for a friend.

**Comment by dotsdl** [comment]
At the moment this can't be done directly, since the 10M atom system alone is 433MB. We would need to use something like github's [large file support](https://git-lfs.github.com/) to directly include them, but this has [big limitations](https://help.github.com/articles/billing-plans-for-git-large-file-storage/) for the no-cost version.

Another option is to include scripts for generating the large systems from the smaller ones. The 10M atom system, for example, is just 6 identical vesicles in a line, right? Perhaps write a nice python function+script that lets you easily construct a system of any combination of the smaller, included systems in a line? That way when want to test with a 10M atom system we can build it from the building blocks the library already includes.

**Comment by orbeckst** [comment]
See also MDAnalysis/mdanalysis#212

**Comment by orbeckst** [comment]
Options for depositing the data
- [zenodo, single file limit](https://zenodo.org/faq) 2 GB
- [figshare, single file limit](https://support.figshare.com/support/solutions/articles/6000079074-what-are-the-file-size-limits-) 5 GB
- Google drive (ASU has bottomless Drive): [files that can be uploaded](https://support.google.com/drive/answer/37603?hl=en) can be up to 5 TB (but apparently only a limited number of file types are supported so we would have to compress them with zip/tar/gzip)
- Dropbox (ASU has bottomless dropbox): [dropbox has no file size limits](https://www.dropbox.com/en/help/5) (when uploaded through the client, the web interface is limited to 10 GB).
- [ASU Digitial Repository](https://repository.asu.edu/) – not clear yet, need to contact

**Comment by orbeckst** [comment]
I'd like to deposit both individual system structures (GRO or PDB), TPR, XTC (but we can cut them). Which ones?

**Comment by orbeckst** [comment]
I put a zip file with the `system.gro` files for the 1.75M, 3.5M and 10M particle vesicle system on figshare under doi:[10.6084/m9.figshare.3406708](http://doi.org/10.6084/m9.figshare.3406708). The compressed tar file is ~150 MB in size.

**Comment by orbeckst** [comment]
(This issue had been resolved with https://github.com/Becksteinlab/vesicle_library/issues/1#issuecomment-222410330 )

**Comment by orbeckst** [comment]
Addendum:

I uploaded a file with 14 M atoms and 1.2 M lipids to the [SPIDAL parallel trajectory benchmark](https://drive.google.com/open?id=0B4oDtTUU3wo8NkNFR1hEdTJIdm8) Google drive in the new superbig folder; the whole benchmark set is public. You should be able to find the folder at https://drive.google.com/open?id=10yFBdACi9qKQng02TZjMO7nKlH7yrisP

You can easily create your own: load the numpy array and then append a copy of itself shifted by 400 Å in the z direction (I think that's sufficient but check the existing max z), try avoiding overlap. Continue stacking in z to create lattices of vesicles with as many atoms as you like.
